# This instruction does the download of Base Image
FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build

# Add to image to organize images by project
LABEL freelibrary.web.version="Hello World"
LABEL maintainer="PowerSJK"

# React dependencies
RUN apt-get update && apt-get upgrade -y \
    nodejs \
    npm

# Copy source code
COPY ../client/ /home/freeLibrary

WORKDIR /home/freeLibrary

RUN dotnet restore
# RUN dotnet build
RUN dotnet publish -c release -o /app --no-restore

# final stage/image
FROM mcr.microsoft.com/dotnet/aspnet:5.0

WORKDIR /app
COPY --from=build /app .
ENTRYPOINT ["dotnet", "client.dll"]




