# This instruction does the download of Base Image
# FROM <image>[:<tag>]
#
# Add to image to organize images by project
# LABEL com.example.version="0.0.1-alpha"
# LABEL Vendor="Tabajara Inc."
# 
# Execute commands
# RUN apt-get update
# RUN apt-get install -y curl
# 
# Execute your app in container
# Only one CMD is allowed in the file
# CMD ["executable","param1","param2"]
# 
# Ports wich a container listen for connections
# EXPOSE <port>
# 
# Sets environment variable
# ENV VARIABLE_NAME variable_value
# 
# Copy files, directories, to destination
# COPY <source> <target>
#
# Copy files, directories and remote files (from URL) to destination
# ADD <source> <target>
# 
# Expose database, configuration files, files/folders
# VOLUME
# 
# Sets the working directory for other instructions (RUN, CMD, ADD)
# WORKDIR




